In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
raw_df=pd.read_csv("Podcast_data.csv")
raw_df

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
0,0,Mystery Matters,Episode 98,NaN,True Crime,74.81,Thursday,Night,NaN,0.0,Positive,31.41998
1,1,Joke Junction,Episode 26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative,88.01241
2,2,Study Sessions,Episode 16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative,44.92531
3,3,Digital Digest,Episode 45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive,46.27824
4,4,Mind & Body,Episode 86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral,75.61031
...,...,...,...,...,...,...,...,...,...,...,...,...
749995,749995,Learning Lab,Episode 25,75.66,Education,69.36,Saturday,Morning,NaN,0.0,Negative,56.87058
749996,749996,Business Briefs,Episode 21,75.75,Business,35.21,Saturday,Night,NaN,2.0,Neutral,45.46242
749997,749997,Lifestyle Lounge,Episode 51,30.98,Lifestyle,78.58,Thursday,Morning,84.89,0.0,Negative,15.26000
749998,749998,Style Guide,Episode 47,108.98,Lifestyle,45.39,Thursday,Morning,93.27,0.0,Negative,100.72939
749999,749999,Sports Central,Episode 99,24.10,Sports,22.45,Saturday,Night,36.72,0.0,Neutral,11.94439

In [3]:
raw_df.isnull().sum()

id                                  0
Podcast_Name                        0
Episode_Title                       0
Episode_Length_minutes          87093
Genre                               0
Host_Popularity_percentage          0
Publication_Day                     0
Publication_Time                    0
Guest_Popularity_percentage    146030
Number_of_Ads                       1
Episode_Sentiment                   0
Listening_Time_minutes              0
dtype: int64

In [4]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 12 columns):
id                             750000 non-null int64
Podcast_Name                   750000 non-null object
Episode_Title                  750000 non-null object
Episode_Length_minutes         662907 non-null float64
Genre                          750000 non-null object
Host_Popularity_percentage     750000 non-null float64
Publication_Day                750000 non-null object
Publication_Time               750000 non-null object
Guest_Popularity_percentage    603970 non-null float64
Number_of_Ads                  749999 non-null float64
Episode_Sentiment              750000 non-null object
Listening_Time_minutes         750000 non-null float64
dtypes: float64(5), int64(1), object(6)
memory usage: 68.7+ MB

In [5]:
raw_df.describe()

,id,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,750000.000000,662907.000000,750000.000000,603970.000000,749999.000000,750000.000000
mean,374999.500000,64.504738,59.859901,52.236449,1.348855,45.437406
std,216506.495284,32.969603,22.873098,28.451241,1.151130,27.138306
min,0.000000,0.000000,1.300000,0.000000,0.000000,0.000000
25%,187499.750000,35.730000,39.410000,28.380000,0.000000,23.178350
50%,374999.500000,63.840000,60.050000,53.580000,1.000000,43.379460
75%,562499.250000,94.070000,79.530000,76.600000,2.000000,64.811580
max,749999.000000,325.240000,119.460000,119.910000,103.910000,119.970000

In [6]:
raw_df.dropna(inplace=True)

In [7]:
raw_df.isna().sum()

id                             0
Podcast_Name                   0
Episode_Title                  0
Episode_Length_minutes         0
Genre                          0
Host_Popularity_percentage     0
Publication_Day                0
Publication_Time               0
Guest_Popularity_percentage    0
Number_of_Ads                  0
Episode_Sentiment              0
Listening_Time_minutes         0
dtype: int64

In [8]:
raw_df.describe()

,id,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
count,539048.000000,539048.000000,539048.000000,539048.000000,539048.000000,539048.000000
mean,375144.243800,64.556952,59.728964,52.234021,1.324945,45.811258
std,216466.180115,32.891153,22.844111,28.510395,1.155997,27.231153
min,1.000000,1.240000,1.300000,0.000000,0.000000,0.000000
25%,187832.500000,35.950000,39.360000,28.260000,0.000000,23.312680
50%,375374.000000,63.670000,59.750000,53.630000,1.000000,43.759825
75%,562594.250000,94.020000,79.370000,76.690000,2.000000,65.192515
max,749999.000000,325.240000,119.460000,115.620000,103.910000,119.970000

In [9]:
raw_df.drop(["id"],axis=1,inplace=True)

In [10]:
raw_df.head()

,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
1,Joke Junction,Episode 26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative,88.01241
2,Study Sessions,Episode 16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative,44.92531
3,Digital Digest,Episode 45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive,46.27824
4,Mind & Body,Episode 86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral,75.61031
6,Criminal Minds,Episode 47,69.83,True Crime,35.82,Sunday,Night,39.02,0.0,Neutral,64.75024

In [11]:
raw_df["Listening_Time_minutes"].value_counts().sort_index()

0.00000      4967
0.00056         2
0.00175         7
0.00661        13
0.01050         5
             ...
119.78000      10
119.79000       8
119.80000      14
119.90000      11
119.97000      19
Name: Listening_Time_minutes, Length: 42733, dtype: int64

In [12]:
pd.set_option("max_rows",None)

In [13]:
from Univariate import Univariate

In [14]:
quan,qual=Univariate.quanQual(raw_df)

In [15]:
quan

['Episode_Length_minutes',
 'Host_Popularity_percentage',
 'Guest_Popularity_percentage',
 'Number_of_Ads',
 'Listening_Time_minutes']

In [16]:
descriptive=Univariate.descriptive(raw_df,quan)
descriptive

,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
Max,325.24,119.46,115.62,103.91,119.97
Min,1.24,1.3,0,0,0
Mean,64.557,59.729,52.234,1.32495,45.8113
Median,63.67,59.75,53.63,1,43.7598
Mode,34.4,38.68,68.53,0,0
Q1:25%,35.95,39.36,28.26,0,23.3127
Q2:50%,63.67,59.75,53.63,1,43.7598
Q3:75%,94.02,79.37,76.69,2,65.1925
Q4:100%,325.24,119.46,115.62,103.91,119.97
IQR,58.07,40.01,48.43,2,41.8798
1.5IQR,87.105,60.015,72.645,3,62.8198
lesserRange,-51.155,-20.655,-44.385,-3,-39.5071
greaterRange,181.125,139.385,149.335,5,128.012

In [17]:
lesser,greater=Univariate.findOutlier(descriptive,quan)

In [18]:
lesser

[]

In [19]:
greater

['Episode_Length_minutes', 'Number_of_Ads']

In [20]:
replaced_df=Univariate.replaceOutlier(raw_df,descriptive,lesser,greater,quan)

D:\HopeAI\9.Capstone Project - DS & ML\Univariate.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnName][dataset[columnName]>descriptive[columnName]['greaterRange']]=descriptive[columnName]['greaterRange']

In [21]:
quan,qual=Univariate.quanQual(replaced_df)
descriptive=Univariate.descriptive(replaced_df,quan)
descriptive

,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Listening_Time_minutes
Max,181.125,119.46,115.62,5,119.97
Min,1.24,1.3,0,0,0
Mean,64.5567,59.729,52.234,1.32384,45.8113
Median,63.67,59.75,53.63,1,43.7598
Mode,34.4,38.68,68.53,0,0
Q1:25%,35.95,39.36,28.26,0,23.3127
Q2:50%,63.67,59.75,53.63,1,43.7598
Q3:75%,94.02,79.37,76.69,2,65.1925
Q4:100%,181.125,119.46,115.62,5,119.97
IQR,58.07,40.01,48.43,2,41.8798
1.5IQR,87.105,60.015,72.645,3,62.8198
lesserRange,-51.155,-20.655,-44.385,-3,-39.5071
greaterRange,181.125,139.385,149.335,5,128.012

In [22]:
lesser,greater=Univariate.findOutlier(descriptive,quan)

In [23]:
greater

[]

In [24]:
replaced_df.to_csv('Preprocessed_Podcast_data.csv', index=False)